function [ fieldNames ] = getFieldNames( )
    fieldNames = {'County', 'Town', 'ChildName', ...
        'Sex', 'Twin', 'Number', 'Alive', 'DOB', ...
        'FatherName', 'FatherAddress1', 'FatherAddress2', ...
        'FatherRace', 'FatherAge', 'FatherBirthplace', ...
        'FatherOccupation', ...
        'MotherName', 'MotherAddress1', 'MotherAddress2', ...
        'MotherRace', 'MotherAge', 'MotherBirthplace', ...
        'MotherOccupation', ...
        'AttendantName', 'AttendantOccupation','AttendantAddress1', ...
        'AttendantAddress2', 'AttendantDated', 'AttendantAttended'};
 end

