function [BW,maskedImage] = segmentImage(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 01-Apr-2016
%----------------------------------------------------


% Initialize segmentation with threshold
mask = im<130;
BW = mask;

% Form masked image from input image and segmented image.
maskedImage = 255 - im;
maskedImage(~BW) = 0;
end
